### ISSUE TITLE
Document alternative projects to polyfill WeakMap/WeakReference

### ISSUE THREAD

**Issue by TysonAndre** [BenMorel/weakmap-polyfill#3]
When php 8.2 (and 9.0) is released and deprecates support for undeclared dynamic properties there may be more interest in using WeakMap, and installations using older php versions (e.g. LTS OS releases) may benefit from polyfills to use newer library releases, if libraries end up switching to WeakMap.

I recently published https://pecl.php.net/package/weakreference_bc for PHP 7.0-7.4 - it passes the same tests as php-src's implementation, though it hasn't had real-world usage yet.

----

Aside: If https://github.com/BenMorel/weakmap-polyfill/blob/master/src/WeakMap.php is used with hundreds of thousands of entries (to replace dynamic properties on hundreds of thousands of objects), it seems like it may see performance degradation (amortized thousands of calls to WeakReference->get() per get/set operation, with HOUSEKEEPING_EVERY being 100. Making it a fraction of the WeakMap size when the WeakMap is large enough may help avoid that)

**Comment by BenMorel** [comment]
Hi @TysonAndre! I'd welcome PRs, both for documenting your alternative in the README, and for a dynamic `HOUSEKEEPING_EVERY`!

**Comment by BenMorel** [comment]
#4, #5, #6 merged, and [version 0.3.0](https://github.com/BenMorel/weakmap-polyfill/releases/tag/0.3.0) released.

Closing. Thank you!
