### ISSUE TITLE
Run housekeeping on GC cycle

### ISSUE THREAD

**Issue by mvorisek** [BenMorel/weakmap-polyfill#9]
When `gc_collect_cycles()` (or implicit GC cycle) is run, housekeeping should be enforced.

I belive it is possible to do so by creating two objects recursively linked - to create a cycle - and weakly referencing the map. In one of the object have a destructor. When GC is triggered, the destructor can dereference the map and force a housekeeping. Before the code returns, a new two recursively linked objects must be created to keep this working...

here is working code: ~https://3v4l.org/l2AVH~ https://3v4l.org/Dpbqa

**Comment by BenMorel** [comment]
Hi @mvorisek, I like your idea, it's very clever, and could be a nice addition to this polyfill!

That being said, I'm wondering if this polyfill is still useful today? PHP 7.4 has been EOL for more than 1 year now...

**Comment by mvorisek** [comment]
In atk4/data we use this polyfill:
- currently for mapping objects to temporary scalars to be able to work with objects in RDBMS - https://github.com/atk4/data/blob/5.0.0/src/Type/LocalObjectType.php#L27,
- and soon for caching data until source object is released - https://github.com/atk4/data/commit/4149b269d73622addba0f932e0980df4887fe43b.

The project supports PHP 7.4 as a lot of users still use that library in legacy apps running still on PHP 7.4.
